CPP 第一章
cheung4843/LMcpsBook pull request #7
Opened 2024-01-30 16:02 UTC by bloodnighttw

第一章部分內容
還在寫 請勿merge

2024-01-31 15:11 UTC, bloodnighttw commented
@cheung4843  
我想可以開始檢查內容合不合適
以及有沒有錯字了
接下來只剩下練習的部分還沒加

2024-01-31 15:22 UTC, bloodnighttw commented
忘記講到format的部分
不知道這可以在哪邊講

2024-01-31 15:53 UTC, bloodnighttw commented
format的部分後面再補上好了

2024-01-31 15:54 UTC, bloodnighttw commented
@cheung4843  pls review

2024-01-31 16:23 UTC, cheung4843 requested changes
大致掃過去而已，實際上部署上去後會再看一次。

2024-01-31 16:23 UTC, cheung4843 commented on docs/fundamental/cpp/hello_world.md
> +在這段程式中，已經有許多稍微複雜的概念，但這邊礙於篇幅，以及講了你也聽不懂，我們就只要了解到:
「但這邊礙於篇幅，以及講了你也聽不懂，」這段可以刪掉。

2024-01-31 16:23 UTC, cheung4843 commented on docs/fundamental/cpp/hello_world.md
> +讓我們焦點放在第六行
讓我們把焦點放在第六行:

2024-01-31 16:23 UTC, cheung4843 commented on docs/fundamental/cpp/hello_world.md
> +    十分不建議你這樣寫，對於程式熟練的人來說，這樣的排版，程式碼讀起來會非常痛苦，對於初學者，也常常會讓你誤會程式碼在做什麼事情。
對於初學者，則容易造成誤解程式碼。

2024-01-31 16:23 UTC, cheung4843 commented on docs/fundamental/cpp/hello_world.md
> +假如今天我們輸入的一連數字，則程式碼改成這樣。
則程式碼改成這樣:

2024-01-31 16:23 UTC, cheung4843 commented on docs/fundamental/cpp/hello_world.md
> +
<img width="247" alt="image" src="https://github.com/cheung4843/LMcpsBook/assets/46809977/10e000cf-d0e4-402f-87a8-62a838b9f60c">
我只標這一區塊的程式碼，也要記得"Reformat"其他的程式碼。

2024-01-31 16:23 UTC, cheung4843 commented on docs/fundamental/cpp/hello_world.md
> +    ```cpp linenums="1"
建議把 `temp` 改成 `word`，符合題幹敘述。

2024-02-01 11:17 UTC, bloodnighttw commented on docs/fundamental/cpp/hello_world.md
> +在這段程式中，已經有許多稍微複雜的概念，但這邊礙於篇幅，以及講了你也聽不懂，我們就只要了解到:
Fixed in [9c67e58](https://github.com/cheung4843/LMcpsBook/pull/7/commits/9c67e58336d65a80964ede1ce6aa453a6ca268a6).

2024-02-01 11:21 UTC, bloodnighttw commented on docs/fundamental/cpp/hello_world.md
> +讓我們焦點放在第六行
Fixed in [dea5f5b](https://github.com/cheung4843/LMcpsBook/pull/7/commits/dea5f5b272981bb373214f0474d676c5c0745208)

2024-02-01 11:22 UTC, bloodnighttw commented on docs/fundamental/cpp/hello_world.md
> +    十分不建議你這樣寫，對於程式熟練的人來說，這樣的排版，程式碼讀起來會非常痛苦，對於初學者，也常常會讓你誤會程式碼在做什麼事情。
Fixed in [139f85e](https://github.com/cheung4843/LMcpsBook/pull/7/commits/139f85e26e449fe691e297d184be9e114768199e)

2024-02-01 11:22 UTC, bloodnighttw commented on docs/fundamental/cpp/hello_world.md
> +假如今天我們輸入的一連數字，則程式碼改成這樣。
Fixed in [7f6a17d](https://github.com/cheung4843/LMcpsBook/pull/7/commits/7f6a17da0fd708ff73e47c4b6005223a35435eb4)

2024-02-01 11:23 UTC, bloodnighttw commented on docs/fundamental/cpp/hello_world.md
> +    ```cpp linenums="1"
Fixed in [2dc76bc](https://github.com/cheung4843/LMcpsBook/pull/7/commits/2dc76bcd04998a4b5f8e90782cb9436948c2864c)

2024-02-01 11:39 UTC, cheung4843 commented on docs/fundamental/cpp/hello_world.md
> +
```cpp
int main() {
    string str1, str2;
    getline(cin, str1);
    cout << str1 + str2 << endl;
    return 0;
}
```
逗號後要空一格。
你提的也算是，找一個可以Reformat的extension用看看。

2024-02-01 11:45 UTC, bloodnighttw commented on docs/fundamental/cpp/hello_world.md
> +
了解 可以merge了

2024-02-01 11:45 UTC, merged